arm:
	armv7l-timesys-linux-gnueabi-gcc -g rsa_tool.c -static -lcrypto -lssl -I /home/eric/iray/projects/toolchain/include/ -L /home/eric/iray/projects/toolchain/lib -o bin/logutil.bin

x86:
	gcc -g -o bin/logutil.bin.x86 rsa_tool.c -lcrypto -lssl
